version: '3'
services:
  node:
    image: 'node:10-alpine'
    volumes:
      - './:/home/node/app'
    working_dir: '/home/node/app'
    ports:
      - '4000-4000'
    command: 'npm install && npm start'